language: java
before_deploy: 
  - echo $(date +%F' '%T)
  - ls build/libs/
deploy:
  provider: releases
  api_key: build/libs/*.jar
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    branch: master