language: java
before_deploy: 
  - echo $(date +%F' '%T)
  - ls build/libs/
deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file: build/libs/*.jar
  skip_cleanup: true
  on:
    branch: master